#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
  update-initramfs -c -k "$2" || true
  if command -v update-grub >/dev/null 2>&1; then
    update-grub || true
  elif command -v grub-mkconfig >/dev/null 2>&1; then
    grub-mkconfig -o /boot/grub/grub.cfg || true
  fi
fi
exit 0
